/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestingUtilities.java
 *
 * Created on 5/06/2012, 12:16:56 PM
 */

package com.coder;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jmendoza
 */
public class TestingUtilities extends javax.swing.JFrame {

    /** Creates new form TestingUtilities */
    public TestingUtilities() {
        initComponents();
        coder = new EasyCoder();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jspTextoOriginal = new javax.swing.JScrollPane();
        jTxaTextoOriginal = new javax.swing.JTextArea();
        jspResultado = new javax.swing.JScrollPane();
        jTxaResultado = new javax.swing.JTextArea();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnProcesar = new javax.swing.JButton();
        jrbtCodificar = new javax.swing.JRadioButton();
        jrbtDecodificar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jspTextoOriginal.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto Original"));

        jTxaTextoOriginal.setColumns(20);
        jTxaTextoOriginal.setRows(5);
        jspTextoOriginal.setViewportView(jTxaTextoOriginal);

        jspResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTxaResultado.setColumns(20);
        jTxaResultado.setRows(5);
        jspResultado.setViewportView(jTxaResultado);

        jbtnLimpiar.setMnemonic(KeyEvent.VK_L);
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnProcesar.setMnemonic(KeyEvent.VK_P);
        jbtnProcesar.setText("Procesar");
        jbtnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcesarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtCodificar);
        jrbtCodificar.setMnemonic(KeyEvent.VK_C);
        jrbtCodificar.setText("Codificar");

        buttonGroup1.add(jrbtDecodificar);
        jrbtDecodificar.setMnemonic(KeyEvent.VK_D);
        jrbtDecodificar.setText("Decodificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspTextoOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jspResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnProcesar)
                        .addGap(18, 18, 18)
                        .addComponent(jrbtCodificar)
                        .addGap(18, 18, 18)
                        .addComponent(jrbtDecodificar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnLimpiar, jbtnProcesar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspTextoOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnProcesar)
                    .addComponent(jrbtCodificar)
                    .addComponent(jrbtDecodificar)
                    .addComponent(jbtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcesarActionPerformed
        if(!jrbtCodificar.isSelected() && !jrbtDecodificar.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de procesamiento", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (jrbtCodificar.isSelected()) {
            if("".equals(jTxaTextoOriginal.getText().trim()))
                JOptionPane.showMessageDialog(this, "Ingrese texto para realizar la operacion", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            jTxaResultado.setText(coder.fusionEncode(jTxaTextoOriginal.getText()));
        } else {
            if("".equals(jTxaTextoOriginal.getText().trim()))
                JOptionPane.showMessageDialog(this, "Ingrese texto para realizar la operacion", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            jTxaResultado.setText(coder.fusionDecode(jTxaTextoOriginal.getText()));
        }        
    }//GEN-LAST:event_jbtnProcesarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        jTxaTextoOriginal.setText("");
        jTxaResultado.setText("");
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingUtilities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea jTxaResultado;
    private javax.swing.JTextArea jTxaTextoOriginal;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnProcesar;
    private javax.swing.JRadioButton jrbtCodificar;
    private javax.swing.JRadioButton jrbtDecodificar;
    private javax.swing.JScrollPane jspResultado;
    private javax.swing.JScrollPane jspTextoOriginal;
    // End of variables declaration//GEN-END:variables
    private EasyCoder coder;
}
